### PR TITLE
new ports and updates

### PR DESCRIPTION
**Pull request by gman999**
mail/p5-Mail-IMAPTalk to 4.01

mail/p5-MIME-Lite-HTML to 1.24

news/newsfish NEW

www/p5-Dancer to 1.3142

### CODE REVIEW

**Comment by jcvernaleo** [comment]
Was there are reason for the removal of
MASTER_SITES=  ${MASTER_SITE_PYPI:=p/python-gnupg/}
in security/py-gnupg/Makefile
WIthout that it fails at the fetch stage for me.

**Comment by jcvernaleo** [comment]
Also a bunch of CVS directories snuck in there somehow:
jcv@ryu ports $ find . -name CVS
./databases/pgbadger/pkg/CVS
./mail/p5-MIME-Lite-HTML/pkg/CVS
./mail/p5-MIME-Lite-HTML/CVS
./mail/p5-Mail-IMAPTalk/pkg/CVS
./mail/p5-Mail-IMAPTalk/CVS
./security/py-gnupg/CVS
./security/py-gnupg/pkg/CVS
./www/p5-HTTP-Lite/pkg/CVS
./www/p5-Dancer/pkg/CVS
./www/p5-Dancer/CVS

**Comment by jcvernaleo** [comment]
Other than those two issues it looks good to me.  So fix them and I'll get it in.

**Comment by gman999** [comment]
I cleared up some of those CVS dirs, but I guess there were more.  My bad.

In terms of the Python ports and MASTER_SITES, some OpenBSD ports do not list a MASTER_SITE, including security/py-gnupg, security/py-M2Crypto, security/py-openssl, but rather I think the Make variable of "MODPY_PI = yes" deals with the templated master site.  I can't seem to locate it though ATM.

But MASTER_SITES do seem to be listed for the BitRig ports.

I'll look into it.

**Comment by gman999** [comment]
more port updates and a type correction

**Comment by gman999** [comment]
pushing it along. . . but they need testing on bitrig.

**Comment by gman999** [comment]
done for now.  Enjoy jcv.

**Comment by gman999** [comment]
open

**Comment by jcvernaleo** [comment]
Looks good (and tested good).  I committed it (and closing manually since github doesn't love me).

Thanks!

**Pull request closed without merging**
