### PR TITLE
Added version 3.9.1

### PR DESCRIPTION
**Pull request by 4mig4**
This is the new version of Regina. Possibly the 2 others could be removed.

### CODE REVIEW

**Comment by jcvernaleo** [comment]
Looks good to me.  I'll merge and push.

**Comment by jcvernaleo** [comment]
It builds too, doesn't just look good :)

**Comment by jcvernaleo** [comment]
Author:     Charlie Root <root@bitrig-update.rural-networks.lan>

@4mig4 want me to change that to your usual commit name (Author:     4mig4 <Christophe Prevotaux c.prevotaux@rural-networks.com>) before I push?

**Comment by 4mig4** [comment]
Yes sure

**Comment by 4mig4** [comment]
I made my email the bitrig one just now use that

**Comment by jcvernaleo** [comment]
It is in, so closing PR.

**Pull request closed without merging**
