### PR TITLE
slashdot mentioned hack fonts and profont, with fonts/Makefile change

### PR DESCRIPTION
**Pull request by gman999**
three more

### CODE REVIEW

**Comment by jcvernaleo** [comment]
@gman999 It looks like hack-font-ttf and hack-font-otf are the same thing:

jcv@ryu fonts $ cat hack-font-ttf/distinfo 
SHA256 (Hack-v2_010-ttf.zip) = 0oeC/DFU/N2pffZv/BOLCH0PEkny2eg9MtIJp5NehJM=
SIZE (Hack-v2_010-ttf.zip) = 683457
jcv@ryu fonts $ cat hack-font-otf/distinfo 
SHA256 (Hack-v2_010-ttf.zip) = 0oeC/DFU/N2pffZv/BOLCH0PEkny2eg9MtIJp5NehJM=
SIZE (Hack-v2_010-ttf.zip) = 683457

Is that a mistake in otf?

**Comment by jcvernaleo** [comment]
Looks good.  There was a minor typo in font/Makefile.  I'll fix it and commit this but if you sent the same packages elsewhere you may want to fix:
diff --git a/fonts/Makefile b/fonts/Makefile
index 0d799a0..2d9fdea 100644
--- a/fonts/Makefile
+++ b/fonts/Makefile
@@ -85,7 +85,7 @@
      SUBDIR += noto-sans-coptic
      SUBDIR += noto-sans-cypriot
      SUBDIR += noto-sans-devanagari
-     SUBDIR += noto-sans-egyptian-hierglyphs
+     SUBDIR += noto-sans-egyptian-hieroglyphs
      SUBDIR += noto-sans-ethiopic
      SUBDIR += noto-sans-georgian
      SUBDIR += noto-sans-gothic

**Comment by jcvernaleo** [comment]
Committed.  Thanks!

**Comment by gman999** [comment]
Thanks JCV.

**Pull request closed without merging**
