### PR TITLE
add x11/st scrollback feature

### PR DESCRIPTION
**Pull request by strake**

### CODE REVIEW

**Comment by natano** [comment]
Is this the same patch as available at http://st.suckless.org/patches/st-scrollback.diff ? It would be preferable to not duplicate the patch locally, but pull it from there during build when a specific flavor is activated. See mail/mutt/Makefile for reference how the mechanism works (PATCHFILES, FLAVORS, MASTER_SITES1).

**Comment by strake** [comment]
On 04/01/2015, Martin Natano <notifications@github.com> wrote:
> Is this the same patch as available at
> http://st.suckless.org/patches/st-scrollback.diff ? It would be preferable
> to not duplicate the patch locally, but pull it from there during build when
> a specific flavor is activated.

No, that patch seems against an earlier version, and anyhow introduces
a bogus pointer fault which mine doesn't.

**Comment by jcvernaleo** [comment]
@natano and @strake Where did you two leave this PR?  Should I go and test it or was it waiting on something?

**Comment by strake** [comment]
For my part it's ready to go.

**Comment by jcvernaleo** [comment]
Had to rebase it with the latest master so this didn't automatically close, but it looks good and works for me so it is in.  Thanks!

**Pull request closed without merging**
