### PR TITLE
Added patches from pkgsrc repo and unbroke freehdl

### PR DESCRIPTION
**Pull request by 4mig4**
Please verify

### CODE REVIEW

**Comment by jcvernaleo** [comment]
This one fails to build.  make works (so your patches are good) but make package does not:
jcv@ryu freehdl $ make package
make: don't know how to make /usr/ports/packages/.tgz (prerequisite of: /usr/ports/packages/amd64/all/freehdl-0.0.7p2)
Stop in .
*** Error 2 in . (/usr/ports/infrastructure/mk/bsd.port.mk:2494 '_internal-package')
*** Error 1 in /usr/ports/lang/freehdl (/usr/ports/infrastructure/mk/bsd.port.mk:2474 'package')

**Comment by jcvernaleo** [comment]
Also a bunch of whitespace after the REVISION which you should remove.

**Comment by 4mig4** [comment]
Ok I will look at that

**Comment by 4mig4** [comment]
fixed I think, try it

**Comment by jcvernaleo** [comment]
I pushed a squashed version of this so closing the PR.  Thanks!

**Pull request closed without merging**
